# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20190221_0049'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_trip', to='login_register.User'),
            preserve_default=False,
        ),
    ]
