# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='desination',
            new_name='destination',
        ),
    ]
