# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20190221_0049'),
        ('trips', '0003_auto_20190227_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attendes',
            field=models.ManyToManyField(related_name='attending', to='login_register.User'),
        ),
    ]
